#!/usr/bin/env python

import re
import os
import random
from argparse import ArgumentParser

from table import LeetDict

def main(args):
    t=LeetDict(args.file, args.random_result)

    print t.translate(args.words)

def parse_args():
    parser = ArgumentParser()
    parser.add_argument("-f", "--file", dest="file")
    parser.add_argument("-w", "--words", dest="words")
    parser.add_argument("-c", "--count", dest="filename",
                      action="store_true")
    parser.add_argument("-r", "--random-result", dest="random_result",
                      action="store_true")

    return parser.parse_args()

if __name__ == '__main__':
    main(parse_args())

